#!/usr/bin/env bash
# Uses SCP to transfer file
# argv[0] - path to file to be transferred
# argv[1] - IP of server to be transferred to
# argv[2] - username scp connects with
# argv[3] - path to SSH private key that scp uses
# example: ./0-transfer_file ~/.ssh/web01 file ubuntu@54.174.125.120
if [ $# -ne 4 ]; then
    echo "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no $4 $1 $3@$2:~/
fi
