#!/usr/bin/env bash
# Sets up load balancer to roundrobin between web01 and web02

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

new="\nfrontend http_web\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend custom_backend\n\nbacke\
nd custom_backend\n\tbalance roundrobin\n\tserver web01 54.174.125.120:80 check\n\tserver web02 34.234.63.53\
:80 check"

sudo echo -e $new | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
