#!/usr/bin/env bash
# Sets up load balancer to roundrobin between web01 and web02

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo apt-get haproxy start

lb="\nfrontend http_web \n\tbind *:80 \n\tstats uri /haproxy?stats \n\tdefault_backend custom_backend \n\nbackend custom_backend \n\tbalance roundrobin \n\tserver web01 34.73.206.41:80 check \n\tserver web02 35.175.196.34:80 check";

sudo echo -e $lb | sudo tee -a /etc/haproxy/haproxy.cfg

# Always use restart instead of start just in case
sudo service haproxy restart
