#!/usr/bin/env bash
# Prints "I am invincible!!!" to interrupt 4-to_infinity_and_beyond
# shellcheck disable=SC2009
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
