#!/usr/bin/env bash
# Prints "Holberton School" 10 times
x=1
while [ $x -le 10 ]
do
	if [ $x == 4 ]
	then
		echo "bad luck"
	elif [ $x == 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((x++))
done
