#!/usr/bin/env bash
# Prints "bad luck" on 4th loop, "good luck" on 8th loop, and "Holberton School" on other loops 1 to 10

x=1
while [ $x -le 10 ]
do
	if [ $x == 4 ]
	then
		echo "bad luck"
	elif [ $x == 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((x++))
done
