#!/usr/bin/env bash
# Prints 1 to 20 but also "bad luck from" country where number is considered bad luck

x=1
while [ $x -le 20 ]
do
	echo $x
	case $x in 
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((x++))
done
